### ISSUE TITLE
 if v.name.split(':')[0] in var_keep_dic: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by hongyanghu** [dBeker/Faster-RCNN-TensorFlow-Python3#116]
Traceback (most recent call last):
  File "C:/Users/huhongyang/Desktop/Faster-RCNN-TensorFlow-Python3-master/train.py", line 216, in <module>
    train.train()
  File "C:/Users/huhongyang/Desktop/Faster-RCNN-TensorFlow-Python3-master/train.py", line 123, in train
    variables_to_restore = self.net.get_variables_to_restore(variables, var_keep_dic)
  File "C:\Users\huhongyang\Desktop\Faster-RCNN-TensorFlow-Python3-master\lib\nets\vgg16.py", line 66, in get_variables_to_restore
    if v.name.split(':')[0] in var_keep_dic:
TypeError: argument of type 'NoneType' is not iterable

**Comment by zhangyue678** [comment]
how to do?

**Comment by hongyanghu** [comment]
你把预训练的vgg_16.ckpt改为vgg16.ckpt。加波好友讨论一下吧------------------ 原始邮件 ------------------
发件人: "zhangyue"<notifications@github.com>
发送时间: 2019年10月27日(星期天) 下午3:42
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3"<Faster-RCNN-TensorFlow-Python3@noreply.github.com>;
抄送: "lincuncuncaogoudan"<997739480@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3]  if v.name.split(':')[0]in var_keep_dic: TypeError: argument of type 'NoneType' is not iterable (#116)



how to do?
 
&mdash;

**Comment by chanstag** [comment]
For me this issue appeared because it was looking for vgg16.ckpt in /data/imagenet_weights but the file was saved as vgg_16.ckpt so I just copied it over to vgg16.ckpt.
