### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'net'. Did you mean: network ?

### ISSUE THREAD

**Issue by xupinjie** [dBeker/Faster-RCNN-TensorFlow-Python3#32]
i run the `demo.py`, then met the problem following:
`
Traceback (most recent call last):
  File "D:/7-xpj/github/Faster-RCNN-TensorFlow-Python3.5-master/demo.py", line 144, in <module>
    net.create_architecture(sess, "TEST", 21, tag='default')
  File "D:\7-xpj\github\Faster-RCNN-TensorFlow-Python3.5-master\lib\nets\network.py", line 283, in create_architecture
    weights_regularizer = tf.contrib.layers.l2_regularizer(cfg.FLAGS.weight_decay)
  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\platform\flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\absl\flags\_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'net'. Did you mean: network ?
`

**Comment by xupinjie** [comment]
just change tf.app.flags.DEFINE_string('network', "vgg16", "The network to be used as backbone") to tf.app.flags.DEFINE_string('net', "vgg16", "The network to be used as backbone") in file \lib\config\config.py
