### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by why4101130** [dBeker/Faster-RCNN-TensorFlow-Python3#36]
When I change the dataset to my own dataset, I will run this error when I run train.py.

I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
voc_2007_trainval gt roidb loaded from D:\python\project\FasterRcnn\FasterRcnn\Faster-RCNN-TensorFlow-Python3.5-master\data\cache\voc_2007_trainval_gt_roidb.pkl
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 209, in <module>
    train = Train()
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 69, in __init__
    self.imdb, self.roidb = combined_roidb("voc_2007_trainval")
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 48, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 48, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 45, in get_roidb
    roidb = get_training_roidb(imdb)
  File "D:/python/project/FasterRcnn/FasterRcnn/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 25, in get_training_roidb
    imdb.append_flipped_images()
  File "D:\python\project\FasterRcnn\FasterRcnn\Faster-RCNN-TensorFlow-Python3.5-master\lib\datasets\imdb.py", line 119, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

Process finished with exit code 1

**Comment by lccate** [comment]
Perhaps you didn't deleate the voc_2007_trainval_gt_roidb.pkl under data/cache

**Comment by gwspotex** [comment]
You can Comment out the" append_flipped_images "
