### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ZJL717** [dBeker/Faster-RCNN-TensorFlow-Python3#6]
D:\Users\JZY0717\Anaconda3\envs\tfenv\python.exe D:/Users/37974/PycharmProjects/Faster-RCNN-TensorFlow-Python3.5-master/train.py
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from D:\Users\37974\PycharmProjects\Faster-RCNN-TensorFlow-Python3.5-master\data\cache\voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
Traceback (most recent call last):
  File "D:/Users/37974/PycharmProjects/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 208, in <module>
    train = Train()
  File "D:/Users/37974/PycharmProjects/Faster-RCNN-TensorFlow-Python3.5-master/train.py", line 70, in __init__
    self.data_layer = RoIDataLayer(self.roidb, self.imdb.num_classes)
  File "D:\Users\37974\PycharmProjects\Faster-RCNN-TensorFlow-Python3.5-master\lib\layer_utils\roi_data_layer.py", line 33, in __init__
    self._shuffle_roidb_inds()
  File "D:\Users\37974\PycharmProjects\Faster-RCNN-TensorFlow-Python3.5-master\lib\layer_utils\roi_data_layer.py", line 45, in _shuffle_roidb_inds
    self._perm = np.random.permutation(np.arange(len(self._roidb)))
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1

**Comment by dBeker** [comment]
It just cannot load the dataset. Please check your paths.
