### ISSUE TITLE
Failed to run python setup.py build_ext --inplace 

### ISSUE THREAD

**Issue by YanShuang17** [dBeker/Faster-RCNN-TensorFlow-Python3#8]

**Comment by YanShuang17** [comment]
just now ,I refered to [this](https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory) , run 
`D:\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat`
then `python setup.py build_ext --inplace` and `python setup.py build_ext install` can be executed successfully . generating a floder named pycocotools.
but I don't know what it is used for?
after I prepared the Imagenet pretrained model and VOC2007dataset, I run the train.py. error occurs:
`F:\clone_from_github\Faster-RCNN-TensorFlow-Python3.5>python train.py
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from lib.datasets.factory import get_imdb
  File "F:\clone_from_github\Faster-RCNN-TensorFlow-Python3.5\lib\datasets\factory.py", line 14, in <module>
    from lib.datasets.pascal_voc import pascal_voc
  File "F:\clone_from_github\Faster-RCNN-TensorFlow-Python3.5\lib\datasets\pascal_voc.py", line 21, in <module>
    from lib.datasets.imdb import imdb
  File "F:\clone_from_github\Faster-RCNN-TensorFlow-Python3.5\lib\datasets\imdb.py", line 18, in <module>
    from lib.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'lib.utils.cython_bbox'`

**Comment by YanShuang17** [comment]
I want to modify it to train my own data.
