### ISSUE TITLE
AssertionError: Single batch only

### ISSUE THREAD

**Issue by Jai-wei** [dBeker/Faster-RCNN-TensorFlow-Python3#96]
Fix VGG16 layers..
Fixed.
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    train.train()
  File "train.py", line 148, in train
    blobs = self.data_layer.forward()
  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\roi_data_layer.py", line 75, in forward
    blobs = self._get_next_minibatch()
  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\roi_data_layer.py", line 71, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\utils\minibatch.py", line 34, in get_minibatch
    assert len(im_scales) == 1, "Single batch only"
AssertionError: Single batch only

how can i solve it?

**Comment by Jai-wei** [comment]
tf.app.flags.DEFINE_integer('ims_per_batch', 1, "Images to use per minibatch")

I find. This is must '1'
