### ISSUE TITLE
Loss is NaN during training after changing some parameters

### ISSUE THREAD

**Issue by Jai-wei** [dBeker/Faster-RCNN-TensorFlow-Python3#97]
I don't think the current version is as good as the python35 version, which has all sorts of weird problems. It has been 2 days since the program was modified, but the problem that loss value is 0 still cannot be solved!

**Comment by morpheusthewhite** [comment]
No one can help you if you don't explain the problem, how you to reproduce it and what was modified

**Comment by Jai-wei** [comment]
> 如果您不解释问题，如何重现问题以及修改内容，没有人可以帮助您

I haven't found the problem yet. When VOC2007 is trained directly from source code, loss is also 0 (or NAN).
python3.6      tensorflow-gpu 1.12.0  RTX2060

**Comment by morpheusthewhite** [comment]
Please speak english.

Paste here the output on terminal when starting `python train.py`

**Comment by Jai-wei** [comment]
> Please speak english.
> 
> Paste here the output on terminal when starting `python train.py`

ok

When I did not modify any files, the results were as follows.
The data set is VOC2007

```log
E:\anaconda36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
wrote gt roidb to E:\Faster-RCNN-TensorFlow-Python3-master\data\cache\voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
2019-08-27 20:11:47.874016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.89GiB
2019-08-27 20:11:47.881629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-08-27 20:11:48.714618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-27 20:11:48.719210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-08-27 20:11:48.722217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-08-27 20:11:48.724738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4634 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From E:\Faster-RCNN-TensorFlow-Python3-master\lib\nets\network.py:57: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
E:\anaconda36\lib\site-packages\tensorflow\python\ops\gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading initial model weights from ./data/imagenet_weights/vgg16.ckpt
Variables restored: vgg_16/conv1/conv1_1/biases:0
Variables restored: vgg_16/conv1/conv1_2/weights:0
Variables restored: vgg_16/conv1/conv1_2/biases:0
Variables restored: vgg_16/conv2/conv2_1/weights:0
Variables restored: vgg_16/conv2/conv2_1/biases:0
Variables restored: vgg_16/conv2/conv2_2/weights:0
Variables restored: vgg_16/conv2/conv2_2/biases:0
Variables restored: vgg_16/conv3/conv3_1/weights:0
Variables restored: vgg_16/conv3/conv3_1/biases:0
Variables restored: vgg_16/conv3/conv3_2/weights:0
Variables restored: vgg_16/conv3/conv3_2/biases:0
Variables restored: vgg_16/conv3/conv3_3/weights:0
Variables restored: vgg_16/conv3/conv3_3/biases:0
Variables restored: vgg_16/conv4/conv4_1/weights:0
Variables restored: vgg_16/conv4/conv4_1/biases:0
Variables restored: vgg_16/conv4/conv4_2/weights:0
Variables restored: vgg_16/conv4/conv4_2/biases:0
Variables restored: vgg_16/conv4/conv4_3/weights:0
Variables restored: vgg_16/conv4/conv4_3/biases:0
Variables restored: vgg_16/conv5/conv5_1/weights:0
Variables restored: vgg_16/conv5/conv5_1/biases:0
Variables restored: vgg_16/conv5/conv5_2/weights:0
Variables restored: vgg_16/conv5/conv5_2/biases:0
Variables restored: vgg_16/conv5/conv5_3/weights:0
Variables restored: vgg_16/conv5/conv5_3/biases:0
Variables restored: vgg_16/fc6/biases:0
Variables restored: vgg_16/fc7/biases:0
Loaded.
Fix VGG16 layers..
Fixed.
2019-08-27 20:12:03.228852: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.09GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:03.238444: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.09GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:03.870430: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:03.879909: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:07.439639: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:07.448312: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:08.880794: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:08.888820: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:09.599769: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:12:09.609253: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
E:\Faster-RCNN-TensorFlow-Python3-master\lib\utils\py_cpu_nms.py:35: RuntimeWarning: invalid value encountered in less_equal
  inds = np.where(ovr <= thresh)[0]
2019-08-27 20:12:10.406047: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: Exception:
Traceback (most recent call last):

  File "E:\anaconda36\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 47, in proposal_target_layer
    rois_per_image, _num_classes)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 135, in _sample_rois
    raise Exception()

Exception


image invalid, skipping
2019-08-27 20:12:10.720552: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: Exception:
Traceback (most recent call last):

  File "E:\anaconda36\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 47, in proposal_target_layer
    rois_per_image, _num_classes)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 135, in _sample_rois
    raise Exception()

Exception
```

**Comment by morpheusthewhite** [comment]
Is that all? Does the program terminate like that? 

It should continue for some time, printing at the end of each epoch loss and other scores.

**Comment by Jai-wei** [comment]
> Please speak english.
> 
> Paste here the output on terminal when starting `python train.py`

But when I modify 'tf.app.flags.DEFINE_float('roi_bg_threshold_low', 0.1' to 0, and 'Pascal_voc' file '
x1 = float(bbox.find('xmin').text) -1 
y1 = float(bbox.find('ymin').text) -1
x2 = float(bbox.find('xmax').text) -1
y2 = float(bbox.find('ymax').text) -1'
to
 'x1 = float(bbox.find('xmin').text)
y1 = float(bbox.find('ymin').text)
x2 = float(bbox.find('xmax').text)
y2 = float(bbox.find('ymax').text)',
the result is as follows:


E:\anaconda36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from E:\Faster-RCNN-TensorFlow-Python3-master\data\cache\voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
2019-08-27 20:18:28.782855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.89GiB
2019-08-27 20:18:28.790735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-08-27 20:18:29.643255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-27 20:18:29.647610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-08-27 20:18:29.650653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-08-27 20:18:29.655328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4634 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From E:\Faster-RCNN-TensorFlow-Python3-master\lib\nets\network.py:57: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
E:\anaconda36\lib\site-packages\tensorflow\python\ops\gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading initial model weights from ./data/imagenet_weights/vgg16.ckpt
Variables restored: vgg_16/conv1/conv1_1/biases:0
Variables restored: vgg_16/conv1/conv1_2/weights:0
Variables restored: vgg_16/conv1/conv1_2/biases:0
Variables restored: vgg_16/conv2/conv2_1/weights:0
Variables restored: vgg_16/conv2/conv2_1/biases:0
Variables restored: vgg_16/conv2/conv2_2/weights:0
Variables restored: vgg_16/conv2/conv2_2/biases:0
Variables restored: vgg_16/conv3/conv3_1/weights:0
Variables restored: vgg_16/conv3/conv3_1/biases:0
Variables restored: vgg_16/conv3/conv3_2/weights:0
Variables restored: vgg_16/conv3/conv3_2/biases:0
Variables restored: vgg_16/conv3/conv3_3/weights:0
Variables restored: vgg_16/conv3/conv3_3/biases:0
Variables restored: vgg_16/conv4/conv4_1/weights:0
Variables restored: vgg_16/conv4/conv4_1/biases:0
Variables restored: vgg_16/conv4/conv4_2/weights:0
Variables restored: vgg_16/conv4/conv4_2/biases:0
Variables restored: vgg_16/conv4/conv4_3/weights:0
Variables restored: vgg_16/conv4/conv4_3/biases:0
Variables restored: vgg_16/conv5/conv5_1/weights:0
Variables restored: vgg_16/conv5/conv5_1/biases:0
Variables restored: vgg_16/conv5/conv5_2/weights:0
Variables restored: vgg_16/conv5/conv5_2/biases:0
Variables restored: vgg_16/conv5/conv5_3/weights:0
Variables restored: vgg_16/conv5/conv5_3/biases:0
Variables restored: vgg_16/fc6/biases:0
Variables restored: vgg_16/fc7/biases:0
Loaded.
Fix VGG16 layers..
Fixed.
2019-08-27 20:18:38.588684: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.09GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:38.599321: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.09GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:39.230656: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:39.237774: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:41.611878: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:41.619476: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:42.369977: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:42.380477: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:43.073925: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-27 20:18:43.081341: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
E:\Faster-RCNN-TensorFlow-Python3-master\lib\utils\py_cpu_nms.py:35: RuntimeWarning: invalid value encountered in less_equal
  inds = np.where(ovr <= thresh)[0]
iter: 5 / 3000, total loss: nan
 >>> rpn_loss_cls: 0.692278
 >>> rpn_loss_box: nan
 >>> loss_cls: 3.125331
 >>> loss_box: 0.000000

speed: 3.292s / iter
iter: 10 / 3000, total loss: nan
 >>> rpn_loss_cls: 0.689376
 >>> rpn_loss_box: nan
 >>> loss_cls: 3.081928
 >>> loss_box: 0.000000

The loss is NAN

**Comment by Jai-wei** [comment]
> Is that all? Does the program terminate like that?
> 
> It should continue for some time, printing at the end of each epoch loss and other scores.

I manually terminated it, but just now I tried it again, and it kept going like this:

image invalid, skipping
2019-08-27 20:23:37.439811: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: Exception:
Traceback (most recent call last):

  File "E:\anaconda36\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 47, in proposal_target_layer
    rois_per_image, _num_classes)

  File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 135, in _sample_rois
    raise Exception()

Exception

**Comment by Jai-wei** [comment]
> Is that all? Does the program terminate like that?
> 
> It should continue for some time, printing at the end of each epoch loss and other scores.

Do you have the 2018 version? That version is available only in python3.5

**Comment by morpheusthewhite** [comment]
> But when I modify 'tf.app.flags.DEFINE_float('roi_bg_threshold_low', 0.1' to 0, and 'Pascal_voc' file '
> x1 = float(bbox.find('xmin').text) -1
> y1 = float(bbox.find('ymin').text) -1
> x2 = float(bbox.find('xmax').text) -1
> y2 = float(bbox.find('ymax').text) -1'
> to
> 'x1 = float(bbox.find('xmin').text)
> y1 = float(bbox.find('ymin').text)
> x2 = float(bbox.find('xmax').text)
> y2 = float(bbox.find('ymax').text)',

Looking at the error it seems that the box training fails (in fact box training loss is NaN, it does not make sense, while box test loss is 0). The other scores behave correctly

**Comment by morpheusthewhite** [comment]
> Do you have the 2018 version? That version is available only in python3.5

I use only the latest version, which has a lot of fixes

**Comment by morpheusthewhite** [comment]
> > Is that all? Does the program terminate like that?
> > It should continue for some time, printing at the end of each epoch loss and other scores.
> 
> I manually terminated it, but just now I tried it again, and it kept going like this:
> 
> image invalid, skipping
> 2019-08-27 20:23:37.439811: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: Exception:
> Traceback (most recent call last):
> 
> File "E:\anaconda36\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in **call**
> ret = func(*args)
> 
> File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 47, in proposal_target_layer
> rois_per_image, _num_classes)
> 
> File "E:\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\proposal_target_layer.py", line 135, in _sample_rois
> raise Exception()
> 
> Exception

Make sure to restore the parameters

**Comment by Jai-wei** [comment]
> > But when I modify 'tf.app.flags.DEFINE_float('roi_bg_threshold_low', 0.1' to 0, and 'Pascal_voc' file '
> > x1 = float(bbox.find('xmin').text) -1
> > y1 = float(bbox.find('ymin').text) -1
> > x2 = float(bbox.find('xmax').text) -1
> > y2 = float(bbox.find('ymax').text) -1'
> > to
> > 'x1 = float(bbox.find('xmin').text)
> > y1 = float(bbox.find('ymin').text)
> > x2 = float(bbox.find('xmax').text)
> > y2 = float(bbox.find('ymax').text)',
> 
> Looking at the error it seems that the box training fails (in fact box training loss is NaN, it does not make sense, while box test loss is 0). The other scores behave correctly

But how do I solve this problem? I used to train VOC2007 in Python35 without this error.

**Comment by morpheusthewhite** [comment]
You can use the old version then.

You can download it here https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/archive/2c52d601cae09fba0d9e445cd95d5af95d80d6c9.zip
